#!/bin/sh

source ~/.bashrc

CurrentFolder=`pwd`

mkdir -p $CurrentFolder/BatchSubmit
mkdir -p $CurrentFolder/Work

for COUNT in 25 50 100 200 400 800 1600 3200 6400 12800 25600 51200
do
   for RUN in `seq 1 20`
   do
      echo $COUNT

      COUNT9=`echo $COUNT | MultiplyConst 9`

      Script=$CurrentFolder/BatchSubmit/Script_${COUNT}_${RUN}.sh
      Work=$CurrentFolder/Work/${COUNT}_${RUN}

      mkdir -p $Work

      BatchPrefix > $Script

      echo "cd $Work" >> $Script
      echo "ln -s $CurrentFolder/*cpp ." >> $Script
      echo "ln -s $CurrentFolder/*h ." >> $Script
      echo "sh compile.sh" >> $Script
      echo "time ./PerformFits ${COUNT} ${COUNT9} 0.007 0 -0.008 0 $RUN" >> $Script
      echo "rm PerformFits *.o" >> $Script
   done
done



