#!/bin/sh

CurrentFolder=`pwd`

mkdir -p $CurrentFolder/BatchSubmit

NUMBER=1

for i in Samples/Events_[0-9]*.root
do
   FileName="BatchSubmit/Run_`basename $i`.sh"

   echo "#!/bin/sh" > $FileName
   echo "#$ -S /bin/sh" >> $FileName
   echo "#$ -V" >> $FileName

   echo -n "#$ -q all.q@t3-susy.local" >> $FileName
   for j in 0-0 0-1 0-2 0-3 0-4 0-5 0-6 1-0 1-2 1-3 1-4 1-5 1-6 1-7 1-8 1-9
   do
      echo -n ",all.q@compute-$j.local" >> $FileName
   done
   echo >> $FileName

   echo "" >> $FileName
   echo "export CMS_PATH=/cms/sw; export SCRAM_ARCH=slc5_amd64_gcc462" >> $FileName
   echo "cd ~/CMSSW/CMSSW_5_2_3/src; eval \`/cms/sw/bin/scramv1 runtime -sh\`;" >> $FileName
   echo "" >> $FileName
   echo "cd $CurrentFolder" >> $FileName
   echo "mkdir -p /wntmp/yichen/" >> $FileName
   echo "" >> $FileName

   echo "mkdir -p Work/WorkArea_`basename $i`" >> $FileName
   echo "cd Work/WorkArea_`basename $i`" >> $FileName
   echo "ln -s ../../Normalization.dh ." >> $FileName
   for j in 30 40 50 70 85 100 150 200 250 300 400 500 600 700 850 1000 1500 2000 2500 3000
   do
      k=`echo $j | DivideConst 4`
      NUMBER=`echo $NUMBER | AddConst 1`
      if [[ "$NUMBER" -gt 25 ]];
      then
         NUMBER=1
      fi
      echo "time ../../PerformFits ../../$i $j ../../Samples/BG_2e2mu_125_ddbar_$NUMBER.root $k" >> $FileName
      echo "mv OutputFile.root OutputFile_$j.root" >> $FileName
   done
done



