#!/bin/sh

CurrentFolder=`pwd`

mkdir -p $CurrentFolder/BatchSubmit

for i in HZZ4l_Prophecy4f_125_100K_tree_11521.root
do
   for Start in `seq 1 1000 40001`
   do
      End=`echo $Start | AddConst 999`
      FileName=$CurrentFolder/BatchSubmit/${i}_${Start}_${End}.sh

      echo "#!/bin/sh" > $FileName
      echo "#$ -S /bin/sh" >> $FileName
      echo "#$ -V" >> $FileName
      echo "#$ -q all.q@compute-0-1.local,all.q@compute-0-2.local,all.q@compute-0-6.local,all.q@compute-0-14.local,all.q@compute-1-0.local,all.q@compute-1-4.local,all.q@compute-1-7.local,all.q@compute-1-3.local,all.q@compute-1-2.local,all.q@compute-1-6.local" >> $FileName
      echo "" >> $FileName
      echo "export CMS_PATH=/cms/sw; export SCRAM_ARCH=slc5_amd64_gcc462" >> $FileName
      echo "cd ~/CMSSW/CMSSW_5_2_3/src; eval \`/cms/sw/bin/scramv1 runtime -sh\`;" >> $FileName
      echo "" >> $FileName
      echo "cd $CurrentFolder" >> $FileName
      echo "mkdir -p /wntmp/yichen/" >> $FileName
      echo "" >> $FileName

      echo "time ./Run OriginalSamples/$i $Start $End" >> $FileName
   done
done



