#!/bin/sh

source ~/.bashrc

CurrentFolder=`pwd`

mkdir -p $CurrentFolder/BatchSubmit
mkdir -p $CurrentFolder/BatchResult

BinCount=40
BinMin=0
BinMax=1

for i2 in `seq 1 $BinCount`
do
   for i3 in `seq 1 $BinCount`
   do
      WorkDir="./WorkArea_Fit_13162_${i2}_${i3}"
      FileName="$CurrentFolder/BatchSubmit/Submit_${i2}_${i3}.sh"

      S7="Trees2/SignalAll7TeV.root"
      S8="Trees2/SignalAll8TeV.root"
      B7="Trees2/BackgroundAll7TeV.root"
      B8="Trees2/BackgroundAll8TeV.root"
      Z7="Trees/HZZEventFitFormat_MC_ZJets_8TeV.root"
      Z8="Trees/HZZEventFitFormat_MC_ZJets_8TeV.root"
      G7="Trees/unweighted/HZZEventFitFormat_ggZZ.root"
      G8="Trees/unweighted/HZZEventFitFormat_ggZZ.root"

      F2=`echo $BinMin $BinMax $BinCount $i2 | awk '{print $1 + ($2-$1)/$3*($4-1)}'`
      F3=`echo $BinMin $BinMax $BinCount $i3 | awk '{print $1 + ($2-$1)/$3*($4-1)}'`
      AbsF2=`echo $F2 | awk '{if($1<0) {print -$1} else {print $1}}'`
      AbsF3=`echo $F3 | awk '{if($1<0) {print -$1} else {print $1}}'`
      F1=`echo $AbsF2 $AbsF3 | awk '{print 1-$1-$2}'`
      S2=`echo $F1 $AbsF2 | awk '{print $2/$1}'`
      S3=`echo $F1 $AbsF3 | awk '{print $2/$1}'`
      A2=`echo $S2 $F2 | awk '{print sqrt($1)*(-3.276),$2}' | awk '{if($2<0) {print -$1} else {print $1}}'`
      A3=`echo $S3 $F3 | awk '{print sqrt($1)*(-5.042),$2}' | awk '{if($2<0) {print -$1} else {print $1}}'`
      echo $i2 $A2 $F2
      echo $i3 $A3 $F3

      F23=`echo $AbsF2 $AbsF3 | awk '{print $1+$2}'`
      if [[ `echo "$F23 < 1" | bc` == "1" ]];
      then
         BatchPrefix > $FileName
         echo "" >> $FileName
         echo "mkdir -p $WorkDir" >> $FileName
         echo "" >> $FileName
         echo "pwd" >> $FileName
         echo "" >> $FileName
         echo "cp -r $CurrentFolder/*cpp $WorkDir" >> $FileName
         echo "cp -r $CurrentFolder/*h $WorkDir" >> $FileName
         echo "cp -r $CurrentFolder/Trees $WorkDir" >> $FileName
         echo "cp -r $CurrentFolder/Trees2 $WorkDir" >> $FileName
         echo "cp -r $CurrentFolder/ReducedTrees $WorkDir" >> $FileName
         echo "cp -r $CurrentFolder/OldTrees $WorkDir" >> $FileName
         echo "" >> $FileName
         echo "rm $WorkDir/*.dh" >> $FileName
         echo "ln -s $CurrentFolder/../../BuildMap/13156_CollectNormalization/CombinedNormalization.dh $WorkDir/" >> $FileName
         echo "ln -s $CurrentFolder/../../BuildMap/13156_CollectNormalization/Normalization.dh $WorkDir/" >> $FileName
         echo "ln -s $CurrentFolder/../../BuildMap/13136_SmallBackgroundNormalization/Normalization.dh $WorkDir/OldNormalization.dh" >> $FileName
         echo "" >> $FileName
         echo "cd $WorkDir" >> $FileName
         echo "" >> $FileName
         echo "sh compile.sh" >> $FileName
         echo "" >> $FileName
         echo "cp $S7 S7.root" >> $FileName
         echo "cp $S8 S8.root" >> $FileName
         echo "cp $B7 B7.root" >> $FileName
         echo "cp $B8 B8.root" >> $FileName
         echo "cp $Z7 Z7.root" >> $FileName
         echo "cp $Z8 Z8.root" >> $FileName
         echo "cp $G7 G7.root" >> $FileName
         echo "cp $G8 G8.root" >> $FileName
         echo "" >> $FileName
         echo "./RunLikelihood S7.root B7.root Z7.root G7.root S8.root B8.root Z8.root G8.root $A2 $A3 0 0 0 0 0 -1 NNNNNNNN NNNNNNNN" >> $FileName
         echo "mv LikelihoodFile.root $CurrentFolder/BatchResult/SMLikelihoodFile_${i2}_${i3}.root" >> $FileName
         echo "" >> $FileName
         echo "cd -" >> $FileName
         echo "" >> $FileName
         echo "rm -r $WorkDir/*" >> $FileName
      fi
   done
done


