

ListFile:
	dasgoclient -query 'file dataset=/QCD_pThat-15_Dijet_TuneCP5_5p02TeV_pythia8/RunIIpp5Spring18DR-94X_mc2017_realistic_forppRef5TeV_v1-v1/AODSIM' > FileList

PrepareForSubmission:
	bash MakeSubmit.sh > Submit.condor

