#!/bin/sh

CurrentFolder=`pwd`

mkdir -p $CurrentFolder/BatchSubmit

for i in Events_[0-9]*.root
do
   FileName="BatchSubmit/Run_$i.sh"

   echo "#!/bin/sh" > $FileName
   echo "#$ -S /bin/sh" >> $FileName
   echo "#$ -V" >> $FileName

   echo -n "#$ -q all.q@compute-30-1.local" >> $FileName
   for j in compute-3-10 compute-3-11 compute-3-12 compute-3-4  compute-3-5  compute-3-6  compute-3-7  compute-3-8  compute-3-9 compute-3-2 compute-3-3
   do
      echo -n ",all.q@$j.local" >> $FileName
   done
   echo >> $FileName

   echo "" >> $FileName
   echo "export CMS_PATH=/cms/sw; export SCRAM_ARCH=slc5_amd64_gcc462" >> $FileName
   echo "cd ~/CMSSW/CMSSW_5_2_4/src; eval \`/cms/sw/bin/scramv1 runtime -sh\`;" >> $FileName
   echo "" >> $FileName
   echo "cd $CurrentFolder" >> $FileName
   echo "mkdir -p /wntmp/yichen/" >> $FileName
   echo "" >> $FileName

   echo "mkdir -p Work/WorkArea_$i" >> $FileName
   echo "cd Work/WorkArea_$i" >> $FileName
   echo "ln -s ../../Normalization.dh ." >> $FileName
   echo "time ../../PerformFits ../../$i 1000 ../../Events_Mini.root 0" >> $FileName
done



