#!/bin/sh

CurrentFolder=`pwd`

mkdir -p $CurrentFolder/BatchSubmit
mkdir -p $CurrentFolder/BatchResult

FileBase=HZZ4l_Prophecy4f_125_100K_tree_11521

for i in ExtSig1 ExtSig2 ExtSig3 ExtSig4 ExtSig5 \
   ExtSig12 ExtSig13 ExtSig14 ExtSig15 \
   ExtSig23 ExtSig24 ExtSig25 ExtSig34 ExtSig35 ExtSig45 EffMEE
do
   Type=Signal
   if [[ "$i" == "EffMEE" ]]
   then
      Type=Background
   else
      Type=Signal
   fi

   FileName=$CurrentFolder/BatchSubmit/$i.sh

   echo "#!/bin/sh" > $FileName
   echo "#$ -S /bin/sh" >> $FileName
   echo "#$ -V" >> $FileName
   echo "#$ -q all.q@compute-0-1.local,all.q@compute-0-2.local,all.q@compute-0-6.local,all.q@compute-0-14.local,all.q@compute-1-0.local,all.q@compute-1-4.local,all.q@compute-1-7.local,all.q@compute-1-3.local,all.q@compute-1-2.local,all.q@compute-1-6.local" >> $FileName
   echo "" >> $FileName
   echo "export CMS_PATH=/cms/sw; export SCRAM_ARCH=slc5_amd64_gcc462" >> $FileName
   echo "cd ~/CMSSW/CMSSW_5_2_3/src; eval \`/cms/sw/bin/scramv1 runtime -sh\`;" >> $FileName
   echo "" >> $FileName
   echo "cd $CurrentFolder" >> $FileName
   echo "cp ${FileBase}.root $CurrentFolder/BatchResult/${FileBase}_$i.root" >> $FileName
   echo "" >> $FileName
   
   echo "time ./RunWithInterpolationAndSmear $CurrentFolder/BatchResult/${FileBase}_$i.root ${Type}MapsLarge/All_$i Likelihood_$i Y" >> $FileName
   echo "time ./RunWithInterpolationAndSmear $CurrentFolder/BatchResult/${FileBase}_$i.root ${Type}MapsUpDown/All_${i}_Up LikelihoodUp_$i Y" >> $FileName
   echo "time ./RunWithInterpolationAndSmear $CurrentFolder/BatchResult/${FileBase}_$i.root ${Type}MapsUpDown/All_${i}_Down LikelihoodDown_$i Y" >> $FileName

   echo "" >> $FileName
done


