#!/bin/sh

source ~/.bashrc

CurrentFolder=`pwd`

mkdir -p $CurrentFolder/BatchSubmit
mkdir -p $CurrentFolder/BatchResult

for i in `seq 0 999`
do
   WorkDir="/wntmp/yichen/Work/WorkArea_Fit_13162_${i}"
   FileName="$CurrentFolder/BatchSubmit/Submit_$i.sh"

   BatchPrefix > $FileName
   echo "" >> $FileName
   echo "echo \$HOSTNAME" >> $FileName
   echo "" >> $FileName
   echo "mkdir -p $WorkDir" >> $FileName
   echo "cd $WorkDir" >> $FileName
   echo "" >> $FileName
   echo "pwd" >> $FileName
   echo "" >> $FileName
   echo "cp -r $CurrentFolder/*cpp $WorkDir" >> $FileName
   echo "cp -r $CurrentFolder/*h $WorkDir" >> $FileName
   echo "cp -r $CurrentFolder/Trees $WorkDir" >> $FileName
   echo "cp -r $CurrentFolder/ExoticToys $WorkDir" >> $FileName
   #echo "cp -r $CurrentFolder/ExoticToys2 $WorkDir" >> $FileName
   echo "" >> $FileName
   echo "rm $WorkDir/*.dh" >> $FileName
   echo "ln -s $CurrentFolder/../../BuildMap/13156_CollectNormalization/CombinedNormalization.dh $WorkDir/" >> $FileName
   echo "ln -s $CurrentFolder/../../BuildMap/13156_CollectNormalization/Normalization.dh $WorkDir/" >> $FileName
   echo "" >> $FileName
   echo "sh compile.sh" >> $FileName
   echo "" >> $FileName
   echo "time ./PerformFits Trees/SyncToys_7TeV_SMSignal.root Trees/SyncToys_7TeV_Bkg.root Trees/SyncToys_7TeV_Bkg.root Trees/SyncToys_7TeV_Bkg.root \\" >> $FileName
   echo "   Trees/SyncToys_8TeV_SMSignal.root Trees/SyncToys_8TeV_Bkg.root Trees/SyncToys_8TeV_Bkg.root Trees/SyncToys_8TeV_Bkg.root \\" >> $FileName
   echo "   0 0 0 0 0 0 0 $i" >> $FileName
   echo "mv OutputFile.root $CurrentFolder/BatchResult/SMResult_$i.root" >> $FileName
   echo "" >> $FileName
   # echo "time ./PerformFits Trees/SyncToys_7TeV_ExoticSignal.root Trees/SyncToys_7TeV_Bkg.root Trees/SyncToys_7TeV_Bkg.root Trees/SyncToys_7TeV_Bkg.root \\" >> $FileName
   # echo "   Trees/SyncToys_8TeV_ExoticSignal.root Trees/SyncToys_8TeV_Bkg.root Trees/SyncToys_8TeV_Bkg.root Trees/SyncToys_8TeV_Bkg.root \\" >> $FileName
   # echo "   0 -5.042 0 0 0 0 0 $i" >> $FileName
   # echo "mv OutputFile.root $CurrentFolder/BatchResult/ExoticLikelihoodFile_$i.root" >> $FileName
   # echo "" >> $FileName
   # echo "time ./PerformFits ExoticToys2/SyncToys_7TeV_All_Mixed_fa2.root Trees/SyncToys_7TeV_Bkg.root Trees/SyncToys_7TeV_Bkg.root Trees/SyncToys_7TeV_Bkg.root \\" >> $FileName
   # echo "   ExoticToys2/SyncToys_8TeV_All_Mixed_fa2.root Trees/SyncToys_8TeV_Bkg.root Trees/SyncToys_8TeV_Bkg.root Trees/SyncToys_8TeV_Bkg.root \\" >> $FileName
   # echo "   -3.276 0 0 0 0 0 0 $i" >> $FileName
   # echo "mv OutputFile.root $CurrentFolder/BatchResult/FA2Result_$i.root" >> $FileName
   # echo "" >> $FileName
   echo "rm -r $WorkDir/*" >> $FileName
done



