{
   TChain Tree("pfcandAnalyzer/pfTree", "");

   Tree.AddFile("SampleBadEE/HiForestAOD_1.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_100.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_101.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_102.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_107.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_11.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_110.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_114.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_12.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_124.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_126.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_13.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_132.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_133.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_135.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_137.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_138.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_14.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_141.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_143.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_147.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_148.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_15.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_150.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_153.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_155.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_157.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_163.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_166.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_167.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_17.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_18.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_19.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_20.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_21.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_23.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_24.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_27.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_28.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_29.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_30.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_31.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_32.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_33.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_35.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_36.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_37.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_38.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_4.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_42.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_44.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_45.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_46.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_48.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_49.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_5.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_50.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_51.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_52.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_54.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_55.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_56.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_58.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_60.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_61.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_62.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_64.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_65.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_67.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_68.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_69.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_7.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_73.root");
   // Tree.AddFile("SampleBadEE/HiForestAOD_74.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_75.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_76.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_77.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_78.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_79.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_8.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_80.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_81.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_82.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_83.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_89.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_92.root");
   Tree.AddFile("SampleBadEE/HiForestAOD_94.root");
            
   Tree.Draw("pfPhi:pfEta>>H(100,-2.5,2.5,100,-3.14159,3.14159)", "pfPt > 5 && pfId == 4", "colz");

   H->SetStats(0);
   H->SetTitle("ID = 4, PT > 5.0");
   H->GetXaxis()->SetTitle("#eta");
   H->GetYaxis()->SetTitle("#phi");
}
