export LD_LIBRARY_PATH = /Users/yichen/Programs/root/build/lib:/Users/yichen/FHeadHelperCode/RootMacros

default: TestRun

Execute: PlotJEC.cpp
	CompileRootMacro PlotJEC.cpp Execute

TestRun: Execute
	./Execute
