default: TestRun

Execute: MakePlot.cpp
	CompileRootMacro MakePlot.cpp Execute

TestRun: Execute
	./Execute --l1 Summer16_07Aug2017_V11_MC_L1FastJet_AK4PFchs.txt --l2l3 Summer16_07Aug2017_V11_MC_L2Relative_AK4PFchs.txt --output TestRun.pdf
