#!/bin/sh

CurrentFolder=`pwd`

mkdir -p $CurrentFolder/BatchSubmit

BackgroundCounter=10

for i in Samples/Events_1[0-9]*.root Samples/Spin0*
do
   i=`basename $i`

   TruthString="0 0 0 0 0 0"
   if [[ "$i" == *_16* ]]
   then
      TruthString="3.85 5.05 0 0 0 0"
   fi

   FileName="BatchSubmit/Run_$i.sh"

   # BackgroundCounter=`echo $BackgroundCounter | AddConst 1`
   # if [[ $BackgroundCounter -gt 16 ]]
   # then
   #    BackgroundCounter=10
   # fi
   # Background="Events_2100$BackgroundCounter.root"

   echo "#!/bin/sh" > $FileName
   echo "#$ -S /bin/sh" >> $FileName
   echo "#$ -V" >> $FileName

   echo -n "#$ -q all.q@t3-susy.local" >> $FileName
   for j in compute-1-7  compute-1-5  compute-1-4  compute-1-3  compute-0-6  compute-0-4  compute-0-3  compute-0-2  compute-0-14 compute-0-1 compute-0-0
   do
      echo -n ",all.q@$j.local" >> $FileName
   done
   echo >> $FileName

   echo "" >> $FileName
   echo "export CMS_PATH=/cms/sw; export SCRAM_ARCH=slc5_amd64_gcc462" >> $FileName
   echo "cd ~/CMSSW/CMSSW_5_2_3/src; eval \`/cms/sw/bin/scramv1 runtime -sh\`;" >> $FileName
   echo "" >> $FileName
   echo "cd $CurrentFolder" >> $FileName
   echo "mkdir -p /wntmp/yichen/" >> $FileName
   echo "" >> $FileName
   
   echo "pwd" >> $FileName
   echo "ls ../.." >> $FileName
   echo "ls ../../Samples" >> $FileName

   echo "mkdir -p Work/WorkArea_$i" >> $FileName
   echo "cd Work/WorkArea_$i" >> $FileName
   echo "ln -s ../../Normalization.dh ." >> $FileName
   echo "time ../../PerformFits ../../Samples/$i 25 ../../Events_Mini.root 0 $TruthString" >> $FileName
   echo "mv OutputFile.root OutputFile_25.root" >> $FileName
   echo "time ../../PerformFits ../../Samples/$i 50 ../../Events_Mini.root 0 $TruthString" >> $FileName
   echo "mv OutputFile.root OutputFile_50.root" >> $FileName
   echo "time ../../PerformFits ../../Samples/$i 100 ../../Events_Mini.root 0 $TruthString" >> $FileName
   echo "mv OutputFile.root OutputFile_100.root" >> $FileName
   echo "time ../../PerformFits ../../Samples/$i 200 ../../Events_Mini.root 0 $TruthString" >> $FileName
   echo "mv OutputFile.root OutputFile_200.root" >> $FileName
   echo "time ../../PerformFits ../../Samples/$i 400 ../../Events_Mini.root 0 $TruthString" >> $FileName
   echo "mv OutputFile.root OutputFile_400.root" >> $FileName
   echo "time ../../PerformFits ../../Samples/$i 800 ../../Events_Mini.root 0 $TruthString" >> $FileName
   echo "mv OutputFile.root OutputFile_800.root" >> $FileName
   echo "time ../../PerformFits ../../Samples/$i 1600 ../../Events_Mini.root 0 $TruthString" >> $FileName
   echo "mv OutputFile.root OutputFile_1600.root" >> $FileName
   # echo "time ../../PerformFits ../../Samples/$i 25 ../../Samples/$Background 5 $TruthString" >> $FileName
   # echo "mv OutputFile OutputFile_25" >> $FileName
   # echo "time ../../PerformFits ../../Samples/$i 50 ../../Samples/$Background 10 $TruthString" >> $FileName
   # echo "mv OutputFile OutputFile_50" >> $FileName
   # echo "time ../../PerformFits ../../Samples/$i 100 ../../Samples/$Background 20 $TruthString" >> $FileName
   # echo "mv OutputFile OutputFile_100" >> $FileName
   # echo "time ../../PerformFits ../../Samples/$i 200 ../../Samples/$Background 40 $TruthString" >> $FileName
   # echo "mv OutputFile OutputFile_200" >> $FileName
   # echo "time ../../PerformFits ../../Samples/$i 400 ../../Samples/$Background 80 $TruthString" >> $FileName
   # echo "mv OutputFile OutputFile_400" >> $FileName
   # echo "time ../../PerformFits ../../Samples/$i 800 ../../Samples/$Background 160 $TruthString" >> $FileName
   # echo "mv OutputFile OutputFile_800" >> $FileName
done



