#!/bin/sh

CurrentFolder=`pwd`

mkdir -p $CurrentFolder/BatchSubmit
mkdir -p $CurrentFolder/BatchResult/1125
mkdir -p $CurrentFolder/BatchResult/8125

for iS in `seq 1 100`
do
   for iB in `seq 1 50`
   do
      Tag=`printf "%03d_%03d" ${iS} ${iB}`
      echo $Tag

      FileName=$CurrentFolder/BatchSubmit/BackgroundFits_${Tag}.sh

      echo "#!/bin/sh" > $FileName
      echo "#$ -S /bin/sh" >> $FileName
      echo "#$ -V" >> $FileName

      #### T3SUSY ###
      # echo "#$ -q all.q@compute-0-0.local,all.q@compute-0-1.local,all.q@compute-0-2.local,all.q@compute-0-3.local,all.q@compute-0-4.local,all.q@compute-0-6.local,all.q@compute-1-0.local,all.q@compute-1-4.local,all.q@compute-1-7.local,all.q@compute-1-8.local,all.q@compute-1-9.local,all.q@compute-1-3.local" >> $FileName
      echo "#$ -q all.q@compute-0-1.local,all.q@compute-0-2.local,all.q@compute-0-6.local,all.q@compute-0-14.local,all.q@compute-1-0.local,all.q@compute-1-4.local,all.q@compute-1-7.local,all.q@compute-1-3.local,all.q@compute-1-2.local,all.q@compute-1-6.local" >> $FileName
      # echo "#$ -q all.q@compute-1-2.local,all.q@compute-1-6.local" >> $FileName

      ### T3HIGGS ###
      # echo "#$ -q all.q@compute-2-2.local,all.q@compute-2-4.local,all.q@compute-3-10.local,all.q@compute-3-11.locaal,all.q@compute-3-6.local,all.q@compute-3-7.local,all.q@compute-3-8.local,all.q@compute-3-9.local,all.q@compute-3-2.local,all.q@compute-3-3.local,all.q@compute-3-4.local,all.q@compute-3-5.local,all.q@compute-3-12.local" >> $FileName

      echo "" >> $FileName
      
      echo "export CMS_PATH=/cms/sw; export SCRAM_ARCH=slc5_amd64_gcc462" >> $FileName
      echo "cd ${CMSSW_BASE}/src; eval \`/cms/sw/bin/scramv1 runtime -sh\`;" >> $FileName
      echo "" >> $FileName
      
      echo "cd $CurrentFolder" >> $FileName
      echo "mkdir /wntmp/yichen/" >> $FileName
      echo "" >> $FileName

      echo "time ./RunFits $iS $iB 1125" >> $FileName
      echo "mv FitResults1125_$Tag.root $CurrentFolder/BatchResult/1125/" >> $FileName
      echo "mv FitResults1125_$Tag.pdf $CurrentFolder/BatchResult/1125/" >> $FileName
      echo "" >> $FileName

      echo "time ./RunFits $iS $iB 8125" >> $FileName
      echo "mv FitResults8125_$Tag.root $CurrentFolder/BatchResult/8125/" >> $FileName
      echo "mv FitResults8125_$Tag.pdf $CurrentFolder/BatchResult/8125/" >> $FileName
      echo "" >> $FileName
   done
done


