DHFile="\"Samples/DataAll.dh\""

# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Track\", 20, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"UncorrectedCalo\", 20, \"\", $DHFile)"

# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 7, \"PF\", 15, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 6, \"PF\", 16, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 6, \"PF\", 17, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"PF\", 18, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"PF\", 19, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"PF\", 20, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 22, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 24, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 26, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 28, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 30, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 35, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 40, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"PF\", 50, \"\", $DHFile)"

# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 7, \"Calo\", 15, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 7, \"Calo\", 16, \"\", $DHFile)"
root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 6, \"Calo\", 17, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 6, \"Calo\", 18, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 6, \"Calo\", 19, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 6, \"Calo\", 20, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"Calo\", 22, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 24, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 26, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 28, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 30, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 35, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 40, \"\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"Calo\", 50, \"\", $DHFile)"

# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 6, \"PF\", 15, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 6, \"PF\", 16, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 6, \"PF\", 17, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"PF\", 18, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"PF\", 19, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"PF\", 20, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 22, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 24, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 26, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 28, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 30, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 35, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 40, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"PF\", 50, \"_Eta24\", $DHFile)"

# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 6, \"Calo\", 15, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 6, \"Calo\", 16, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 6, \"Calo\", 17, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"Calo\", 18, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"Calo\", 19, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"Calo\", 20, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"Calo\", 22, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"Calo\", 24, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 26, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 28, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 30, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 35, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 40, \"_Eta24\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"Calo\", 50, \"_Eta24\", $DHFile)"

# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 6, \"PF\", 15, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"PF\", 16, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"PF\", 17, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 18, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 19, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"PF\", 20, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"PF\", 22, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"PF\", 24, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"PF\", 26, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"PF\", 28, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"PF\", 30, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"PF\", 35, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"PF\", 40, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"PF\", 50, \"_Eta10\", $DHFile)"

# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"Calo\", 15, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"Calo\", 16, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 5, \"Calo\", 17, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 18, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 19, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 20, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 22, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 4, \"Calo\", 24, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"Calo\", 26, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"Calo\", 28, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"Calo\", 30, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"Calo\", 35, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"Calo\", 40, \"_Eta10\", $DHFile)"
# root -l -b -q "SimultaneousFit_FloatAll.C+(\"Samples/DataAll.root\", 3, \"Calo\", 50, \"_Eta10\", $DHFile)"





