#define CONST_PI 3.141592653589793238462643383279502884797169399375105820974944
#define CONST_MZ 91.1876
#define CONST_WZ 2.4952
#define CONST_SW2 0.2313
// #define CONST_SW2 0.2397
#define CONST_SW sqrt(CONST_SW2)
#define CONST_CW sqrt(1-CONST_SW2)
#define CONST_MW (CONST_MZ*CONST_CW)
#define CONST_ALPHA (1.0/127.916)
#define CONST_EE sqrt(4*CONST_PI*CONST_ALPHA)
#define CONST_ETA 0.15
// #define CONST_GL (2*(-0.5+CONST_SW2)*sqrt(CONST_PI*CONST_ALPHA/(1-CONST_SW2)/CONST_SW2))
// #define CONST_GR (2*CONST_SW2*sqrt(CONST_PI*CONST_ALPHA/(1-CONST_SW2)/CONST_SW2))
// #define CONST_GL (CONST_LI1*sqrt(CONST_PI*CONST_ALPHA/(1-CONST_SW2)/CONST_SW2))
// #define CONST_GR (CONST_LR1*sqrt(CONST_PI*CONST_ALPHA/(1-CONST_SW2)/CONST_SW2))
// #define CONST_GQL_UP (2*(0.5-(2.0/3)*CONST_SW2)*sqrt(CONST_PI*CONST_ALPHA/(1-CONST_SW2)/CONST_SW2))
// #define CONST_GQR_UP (2*(-2.0/3)*CONST_SW2*sqrt(CONST_PI*CONST_ALPHA/(1-CONST_SW2)/CONST_SW2))
// #define CONST_GQL_DOWN (2*(-0.5+(1.0/3)*CONST_SW2)*sqrt(CONST_PI*CONST_ALPHA/(1-CONST_SW2)/CONST_SW2))
// #define CONST_GQR_DOWN (2*(1.0/3)*CONST_SW2*sqrt(CONST_PI*CONST_ALPHA/(1-CONST_SW2)/CONST_SW2))
// #define CONST_VH 246

#define CONST_TW (CONST_SW/CONST_CW)
#define CONST_LI1 (2*CONST_SW2-1)
#define CONST_RI1 (2*CONST_SW2)
#define CONST_LIU (2*(0.5-CONST_SW2*2/3))
#define CONST_RIU (-2*(CONST_SW2*2/3))
#define CONST_LID (2*(-0.5+CONST_SW2*1/3))
#define CONST_RID (2*(CONST_SW2*1/3))
#define CONST_G1 (2*CONST_GL*CONST_CW/CONST_LI1)
#define CONST_GY (CONST_TW*CONST_G1)
#define CONST_VH (2*CONST_MW/CONST_G1)

#define CONST_GL (CONST_LI1*sqrt(CONST_PI*CONST_ALPHA/(1-CONST_SW2)/CONST_SW2))
#define CONST_GR (CONST_RI1*sqrt(CONST_PI*CONST_ALPHA/(1-CONST_SW2)/CONST_SW2))
#define CONST_GQL_UP (CONST_LIU*sqrt(CONST_PI*CONST_ALPHA/(1-CONST_SW2)/CONST_SW2))
#define CONST_GQR_UP (CONST_RIU*sqrt(CONST_PI*CONST_ALPHA/(1-CONST_SW2)/CONST_SW2))
#define CONST_GQL_DOWN (CONST_LID*sqrt(CONST_PI*CONST_ALPHA/(1-CONST_SW2)/CONST_SW2))
#define CONST_GQR_DOWN (CONST_RID*sqrt(CONST_PI*CONST_ALPHA/(1-CONST_SW2)/CONST_SW2))

#define CONST_GV ((CONST_GL+CONST_GR)/2)
#define CONST_GA ((CONST_GL-CONST_GR)/2)
#define CONST_GQV_UP ((CONST_GQL_UP+CONST_GQR_UP)/2)
#define CONST_GQA_UP ((CONST_GQL_UP-CONST_GQR_UP)/2)
#define CONST_GQV_DOWN ((CONST_GQL_DOWN+CONST_GQR_DOWN)/2)
#define CONST_GQA_DOWN ((CONST_GQL_DOWN-CONST_GQR_DOWN)/2)

#define CONST_NC 3

#include <iostream>

void PrintConstants();

