
RunPrepareSubmission: PrepareSubmission.cpp
	CompileRootMacro PrepareSubmission.cpp RunPrepareSubmission

ExecutePrepareSubmission: RunPrepareSubmission
	./RunPrepareSubmission > SubmitAll.sh

RunPrepareSubmissionBundle: PrepareSubmissionBundle.cpp
	CompileRootMacro PrepareSubmissionBundle.cpp RunPrepareSubmissionBundle

ExecutePrepareSubmissionBundle: RunPrepareSubmissionBundle
	./RunPrepareSubmissionBundle > SubmitAll.sh


