#!/bin/sh

CurrentFolder=`pwd`

mkdir -p $CurrentFolder/BatchSubmit

for i in `ls OriginalSamples | grep root`
do
   FileName=$CurrentFolder/BatchSubmit/$i.sh

   echo "#!/bin/sh" > $FileName
   echo "#$ -S /bin/sh" >> $FileName
   echo "#$ -V" >> $FileName
   echo "#$ -q all.q@compute-0-1.local,all.q@compute-0-2.local,all.q@compute-0-6.local,all.q@compute-0-14.local,all.q@compute-1-0.local,all.q@compute-1-4.local,all.q@compute-1-7.local,all.q@compute-1-3.local,all.q@compute-1-2.local,all.q@compute-1-6.local" >> $FileName
   echo "" >> $FileName
   echo "export CMS_PATH=/cms/sw; export SCRAM_ARCH=slc5_amd64_gcc462" >> $FileName
   echo "cd ~/CMSSW/CMSSW_5_2_3/src; eval \`/cms/sw/bin/scramv1 runtime -sh\`;" >> $FileName
   echo "" >> $FileName
   echo "cd $CurrentFolder" >> $FileName
   echo "mkdir -p /wntmp/yichen/" >> $FileName
   # echo "cp $CurrentFolder/OriginalSamples/$i /wntmp/yichen/" >> $FileName
   echo "cp $CurrentFolder/HalfwaySamples/$i /wntmp/yichen/" >> $FileName
   echo "" >> $FileName
   
   # for j in ExtSig4 ExtSig14 ExtSig34
   # do
   #    echo "time ./RunWithInterpolation /wntmp/yichen/$i SignalMapsUpDown/All_${j}_Up LikelihoodUp_$j Y" >> $FileName
   #    echo "time ./RunWithInterpolation /wntmp/yichen/$i SignalMapsUpDown/All_${j}_Down LikelihoodDown_$j Y" >> $FileName
   # done
      
   # echo "time ./RunWithInterpolation /wntmp/yichen/$i BackgroundMapsLarge/All_EffMEE LikelihoodLarge_EffMEE Y" >> $FileName
   # echo "time ./RunWithInterpolation /wntmp/yichen/$i SignalMapsLarge/All_ExtSig1 LikelihoodLarge_ExtSig1 Y" >> $FileName
   # echo "time ./RunWithInterpolation /wntmp/yichen/$i SignalMapsLarge/All_ExtSig3 LikelihoodLarge_ExtSig3 Y" >> $FileName
   # echo "time ./RunWithInterpolation /wntmp/yichen/$i SignalMapsLarge/All_ExtSig13 LikelihoodLarge_ExtSig13 Y" >> $FileName
   
   echo "time ./RunWithInterpolation /wntmp/yichen/$i SignalMaps/All_ExtSig4 LikelihoodReattach_ExtSig4 Y" >> $FileName

   echo "" >> $FileName
   echo "cp /wntmp/yichen/$i $CurrentFolder/Samples/$i" >> $FileName
done


