#!/bin/sh

CurrentFolder=`pwd`

mkdir -p $CurrentFolder/BatchSubmit

for i in EventB.root Madgraph2e2mu_part1.root Madgraph4e_part1.root
do
   for Start in `seq 0 100 99900`
   do
      End=`echo $Start | AddConst 99`
      FileName=$CurrentFolder/BatchSubmit/${i}_${Start}_${End}.sh

      echo "#!/bin/sh" > $FileName
      echo "#$ -S /bin/sh" >> $FileName
      echo "#$ -V" >> $FileName
      
      echo -n "#$ -q all.q@t3-susy.local" >> $FileName
      for j in 0-0 0-1 0-2 0-3 0-4 0-5 0-6 1-0 1-2 1-3 1-4 1-5 1-6 1-7 1-8 1-9
      do
         echo -n ",all.q@compute-$j.local" >> $FileName
      done
      echo >> $FileName

      echo "" >> $FileName
      echo "export CMS_PATH=/cms/sw; export SCRAM_ARCH=slc5_amd64_gcc462" >> $FileName
      echo "cd ~/CMSSW/CMSSW_5_2_3/src; eval \`/cms/sw/bin/scramv1 runtime -sh\`;" >> $FileName
      echo "" >> $FileName
      echo "cd $CurrentFolder" >> $FileName
      echo "mkdir -p /wntmp/yichen/" >> $FileName
      echo "" >> $FileName

      echo "time ./Run CleanTrees/$i $Start $End" >> $FileName
      echo "time ./RunBackground CleanTrees/$i $Start $End" >> $FileName
   done
done



