#!/bin/sh

svnstatus=`echo 'svn status | grep -v root$ | grep -v pdf$ | grep -v png$ | grep -v eps$ | grep -v MeetingReports/'`

echo "Scanning for all not-in-svn files...."
eval $svnstatus | grep ^?
echo

echo "Removing potentially non-svn-intended files from the above lists...."
eval $svnstatus | grep ^? | grep -v "   Meetings/" | grep -v "   FitCodeFromWill/" | grep -v ".tar.gz$" | \
   grep -v "Json$" | grep -v "JSON$"
echo

echo "Checking if there is any source code not in the svn system...."
eval $svnstatus | grep ^? | grep "\.cpp$"
eval $svnstatus | grep ^? | grep "\.h$"
eval $svnstatus | grep ^? | grep "\.sh$"
echo

echo "Checking if there is any source code not checked in...."
eval $svnstatus | grep ^[MA] | grep "\.cpp$"
eval $svnstatus | grep ^[MA] | grep "\.h$"
eval $svnstatus | grep ^[MA] | grep "\.sh$"
echo

echo "Checking if there's anything else not checked in...."
eval $svnstatus | grep ^[MA] | grep -v "\.cpp$" | grep -v "\.h$"
echo




