#!/bin/sh

Signal=1

if [[ "$Signal" == "1" ]]
then
   Angle1Min=0
   Angle1Max=6.2831853070
   Angle1Difference=`echo $Angle1Max | SubtractConst $Angle1Min`
   NBinsAngle1=10
   Angle1Step=`echo $Angle1Difference | DivideConst $NBinsAngle1`

   Angle2Min=-1
   Angle2Max=1
   Angle2Difference=`echo $Angle2Max | SubtractConst $Angle2Min`
   NBinsAngle2=12
   Angle2Step=`echo $Angle2Difference | DivideConst $NBinsAngle2`
else
   Angle1Min=0
   Angle1Max=6.2831853070
   Angle1Difference=`echo $Angle1Max | SubtractConst $Angle1Min`
   NBinsAngle1=12
   Angle1Step=`echo $Angle1Difference | DivideConst $NBinsAngle1`

   Angle2Min=-1
   Angle2Max=1
   Angle2Difference=`echo $Angle2Max | SubtractConst $Angle2Min`
   NBinsAngle2=15
   Angle2Step=`echo $Angle2Difference | DivideConst $NBinsAngle2`
fi

CurrentFolder=`pwd`

mkdir -p $CurrentFolder/BatchSubmit
mkdir -p $CurrentFolder/BatchResult

for HiggsMass in 100 110 120 125 130 140 160 200 300 400
do
   for iAngle1 in `seq 1 $NBinsAngle1`
   do
      for iAngle2 in `seq 1 $NBinsAngle2`
      do
         Angle1=`echo $iAngle1 | SubtractConst 0.5 | MultiplyConst $Angle1Step | AddConst $Angle1Min`
         Angle2=`echo $iAngle2 | SubtractConst 0.5 | MultiplyConst $Angle2Step | AddConst $Angle2Min`

         Tag="${HiggsMass}_${iAngle1}_${iAngle2}"

         FileName=$CurrentFolder/BatchSubmit/Run_${Tag}.sh

         SkipHeader=Y
         if [ "$iAngle1" -eq 1 ]; then
            if [ "$iAngle2" -eq 1 ]; then
               SkipHeader=N
            fi
         fi

         echo "#!/bin/sh" > $FileName
         echo "#$ -S /bin/sh" >> $FileName
         echo "#$ -V" >> $FileName
         echo "#$ -q all.q@compute-0-1.local,all.q@compute-0-2.local,all.q@compute-0-6.local,all.q@compute-0-14.local,all.q@compute-1-0.local,all.q@compute-1-4.local,all.q@compute-1-7.local,all.q@compute-1-3.local,all.q@compute-1-2.local,all.q@compute-1-6.local" >> $FileName
         echo "" >> $FileName
         echo "export CMS_PATH=/cms/sw; export SCRAM_ARCH=slc5_amd64_gcc462" >> $FileName
         echo "cd $CMSSW_BASE/src; eval \`scramv1 runtime -sh\`;" >> $FileName
         echo "" >> $FileName
         echo "cd $CurrentFolder" >> $FileName
         echo "mkdir /wntmp/yichen/" >> $FileName
         echo "time ./RunMap $HiggsMass $Angle1 $Angle2 ${Tag} $SkipHeader" >> $FileName
         echo "mv /wntmp/yichen/IndividualMap_${Tag}_*.map7 $CurrentFolder/BatchResult/" >> $FileName
         echo "" >> $FileName
      done
   done
done


