

default: TestRun

TestRun:
	python3 Generate.py --mode 1 --seed 20210421 --output ExponentialDesign_20210421.data
	python3 Generate.py --mode 2 --seed 20210421 --output BinomialDesign_20210421.data

