default: ListAllSamples

ListAllSamples:
	dasgoclient -query 'dataset=/RelValQCD_FlatPt_15_3000HS_13/CMSSW_10_5_0_pre*105X_mc2017_realistic_v4_HS_*/*' > DatasetNames.txt

CreateSubmitFiles:
	bash CreateSubmitFiles.sh


