#!/bin/sh

source Setup_FileLocation.sh
mkdir -p $Step2Output

mkdir -p Log
SubmissionFile=Step2.condor

echo "Universe   = vanilla" > $SubmissionFile
echo "Executable = `pwd`/Step2PUMatching.sh" >> $SubmissionFile
echo >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi1.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi10.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi101.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi102.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi104.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi105.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi108.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi109.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi110.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi111.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi1.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi10.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi101.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi102.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi104.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi105.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi108.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi109.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi110.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi111.root $Step2Output 0" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi114.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi117.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi120.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi121.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi122.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi125.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi126.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi127.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi128.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi13.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi114.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi117.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi120.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi121.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi122.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi125.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi126.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi127.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi128.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi13.root $Step2Output 1" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi134.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi138.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi14.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi142.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi143.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi144.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi145.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi146.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi15.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi150.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi134.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi138.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi14.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi142.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi143.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi144.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi145.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi146.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi15.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi150.root $Step2Output 2" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi152.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi155.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi156.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi157.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi161.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi162.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi163.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi165.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi167.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi168.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi152.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi155.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi156.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi157.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi161.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi162.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi163.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi165.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi167.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi168.root $Step2Output 3" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi169.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi173.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi178.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi184.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi185.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi187.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi195.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi197.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi198.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi199.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi169.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi173.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi178.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi184.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi185.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi187.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi195.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi197.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi198.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi199.root $Step2Output 4" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi202.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi203.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi205.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi208.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi209.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi215.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi216.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi219.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi228.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi23.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi202.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi203.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi205.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi208.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi209.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi215.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi216.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi219.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi228.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi23.root $Step2Output 5" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi231.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi234.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi239.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi24.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi245.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi25.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi270.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi278.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi285.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi29.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi231.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi234.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi239.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi24.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi245.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi25.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi270.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi278.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi285.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi29.root $Step2Output 6" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi290.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi291.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi292.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi295.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi297.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi30.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi305.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi315.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi316.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi317.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi290.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi291.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi292.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi295.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi297.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi30.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi305.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi315.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi316.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi317.root $Step2Output 7" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi319.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi320.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi321.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi322.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi324.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi325.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi326.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi327.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi329.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi33.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi319.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi320.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi321.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi322.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi324.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi325.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi326.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi327.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi329.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi33.root $Step2Output 8" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi330.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi331.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi332.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi333.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi335.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi337.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi339.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi343.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi344.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi348.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi330.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi331.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi332.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi333.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi335.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi337.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi339.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi343.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi344.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi348.root $Step2Output 9" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi350.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi351.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi352.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi359.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi36.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi360.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi364.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi368.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi374.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi377.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi350.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi351.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi352.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi359.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi36.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi360.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi364.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi368.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi374.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi377.root $Step2Output 10" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi378.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi379.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi380.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi381.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi383.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi384.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi385.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi386.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi387.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi388.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi378.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi379.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi380.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi381.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi383.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi384.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi385.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi386.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi387.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi388.root $Step2Output 11" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi389.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi39.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi390.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi391.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi395.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi396.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi398.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi4.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi40.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi400.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi389.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi39.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi390.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi391.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi395.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi396.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi398.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi4.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi40.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi400.root $Step2Output 12" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi402.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi403.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi404.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi405.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi406.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi407.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi408.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi409.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi41.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi410.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi402.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi403.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi404.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi405.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi406.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi407.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi408.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi409.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi41.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi410.root $Step2Output 13" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi411.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi412.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi414.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi416.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi417.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi418.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi42.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi420.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi421.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi422.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi411.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi412.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi414.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi416.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi417.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi418.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi42.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi420.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi421.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi422.root $Step2Output 14" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi423.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi424.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi425.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi426.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi427.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi428.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi429.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi430.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi431.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi432.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi423.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi424.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi425.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi426.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi427.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi428.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi429.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi430.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi431.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi432.root $Step2Output 15" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi434.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi435.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi436.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi438.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi439.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi440.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi441.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi443.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi444.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi445.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi434.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi435.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi436.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi438.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi439.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi440.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi441.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi443.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi444.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi445.root $Step2Output 16" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi446.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi447.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi448.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi449.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi45.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi450.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi451.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi452.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi453.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi455.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi446.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi447.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi448.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi449.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi45.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi450.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi451.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi452.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi453.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi455.root $Step2Output 17" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi456.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi457.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi459.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi460.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi461.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi462.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi463.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi465.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi466.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi467.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi456.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi457.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi459.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi460.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi461.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi462.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi463.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi465.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi466.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi467.root $Step2Output 18" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi468.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi471.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi472.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi473.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi474.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi475.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi477.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi478.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi479.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi48.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi468.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi471.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi472.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi473.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi474.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi475.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi477.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi478.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi479.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi48.root $Step2Output 19" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi480.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi481.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi483.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi484.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi485.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi486.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi487.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi490.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi492.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi493.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi480.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi481.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi483.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi484.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi485.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi486.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi487.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi490.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi492.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi493.root $Step2Output 20" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi5.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi513.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi517.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi519.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi52.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi520.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi521.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi526.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi528.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi53.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi5.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi513.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi517.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi519.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi52.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi520.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi521.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi526.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi528.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi53.root $Step2Output 21" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi531.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi534.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi535.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi536.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi537.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi538.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi539.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi540.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi541.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi542.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi531.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi534.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi535.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi536.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi537.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi538.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi539.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi540.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi541.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi542.root $Step2Output 22" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi543.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi544.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi545.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi547.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi549.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi550.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi551.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi552.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi553.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi554.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi543.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi544.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi545.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi547.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi549.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi550.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi551.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi552.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi553.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi554.root $Step2Output 23" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi555.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi556.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi559.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi56.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi560.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi563.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi564.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi566.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi567.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi568.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi555.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi556.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi559.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi56.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi560.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi563.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi564.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi566.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi567.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi568.root $Step2Output 24" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi569.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi57.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi571.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi572.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi574.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi575.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi576.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi577.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi580.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi581.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi569.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi57.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi571.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi572.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi574.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi575.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi576.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi577.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi580.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi581.root $Step2Output 25" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi582.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi583.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi584.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi588.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi59.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi590.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi593.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi594.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi595.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi598.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi582.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi583.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi584.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi588.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi59.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi590.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi593.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi594.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi595.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi598.root $Step2Output 26" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi599.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi6.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi60.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi600.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi601.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi602.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi603.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi604.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi606.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi607.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi599.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi6.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi60.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi600.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi601.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi602.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi603.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi604.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi606.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi607.root $Step2Output 27" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi61.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi610.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi611.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi614.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi615.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi616.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi619.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi62.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi620.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi621.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi61.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi610.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi611.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi614.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi615.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi616.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi619.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi62.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi620.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi621.root $Step2Output 28" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi622.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi623.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi625.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi626.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi627.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi628.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi629.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi63.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi632.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi634.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi622.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi623.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi625.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi626.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi627.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi628.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi629.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi63.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi632.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi634.root $Step2Output 29" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi635.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi636.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi637.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi638.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi639.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi640.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi642.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi643.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi644.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi646.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi635.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi636.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi637.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi638.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi639.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi640.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi642.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi643.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi644.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi646.root $Step2Output 30" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi647.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi649.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi65.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi650.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi651.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi652.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi653.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi654.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi658.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi659.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi647.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi649.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi65.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi650.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi651.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi652.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi653.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi654.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi658.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi659.root $Step2Output 31" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi66.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi660.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi661.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi662.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi663.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi664.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi665.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi666.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi667.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi668.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi66.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi660.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi661.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi662.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi663.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi664.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi665.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi666.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi667.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi668.root $Step2Output 32" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi669.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi67.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi670.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi671.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi672.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi673.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi674.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi675.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi677.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi678.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi669.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi67.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi670.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi671.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi672.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi673.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi674.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi675.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi677.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi678.root $Step2Output 33" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi679.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi680.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi681.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi682.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi683.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi684.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi685.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi687.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi688.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi689.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi679.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi680.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi681.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi682.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi683.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi684.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi685.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi687.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi688.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi689.root $Step2Output 34" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi690.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi692.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi693.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi694.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi695.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi696.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi697.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi698.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi699.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi7.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi690.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi692.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi693.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi694.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi695.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi696.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi697.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi698.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi699.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi7.root $Step2Output 35" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi70.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi700.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi702.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi703.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi704.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi705.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi706.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi708.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi709.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi71.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi70.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi700.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi702.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi703.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi704.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi705.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi706.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi708.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi709.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi71.root $Step2Output 36" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi713.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi714.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi715.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi716.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi718.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi72.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi720.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi721.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi722.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi724.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi713.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi714.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi715.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi716.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi718.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi72.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi720.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi721.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi722.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi724.root $Step2Output 37" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi725.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi726.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi727.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi728.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi729.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi73.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi730.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi732.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi733.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi734.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi725.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi726.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi727.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi728.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi729.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi73.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi730.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi732.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi733.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi734.root $Step2Output 38" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi736.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi737.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi738.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi739.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi742.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi743.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi744.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi746.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi747.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi748.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi736.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi737.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi738.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi739.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi742.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi743.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi744.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi746.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi747.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi748.root $Step2Output 39" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi75.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi750.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi751.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi752.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi753.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi754.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi756.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi757.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi758.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi759.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi75.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi750.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi751.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi752.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi753.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi754.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi756.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi757.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi758.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi759.root $Step2Output 40" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi760.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi763.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi764.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi765.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi766.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi767.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi768.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi769.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi770.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi771.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi760.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi763.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi764.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi765.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi766.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi767.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi768.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi769.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi770.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi771.root $Step2Output 41" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi774.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi775.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi778.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi779.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi78.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi780.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi781.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi783.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi784.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi786.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi774.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi775.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi778.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi779.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi78.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi780.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi781.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi783.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi784.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi786.root $Step2Output 42" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi787.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi788.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi79.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi790.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi791.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi792.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi793.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi794.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi797.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi8.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi787.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi788.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi79.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi790.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi791.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi792.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi793.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi794.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi797.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi8.root $Step2Output 43" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi80.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi800.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi802.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi803.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi804.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi805.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi806.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi807.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi81.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi811.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi80.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi800.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi802.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi803.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi804.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi805.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi806.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi807.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi81.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi811.root $Step2Output 44" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi814.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi815.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi816.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi817.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi818.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi819.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi821.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi823.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi825.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi826.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi814.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi815.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi816.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi817.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi818.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi819.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi821.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi823.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi825.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi826.root $Step2Output 45" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi828.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi829.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi830.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi833.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi834.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi835.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi836.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi837.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi838.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi839.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi828.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi829.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi830.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi833.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi834.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi835.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi836.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi837.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi838.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi839.root $Step2Output 46" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi84.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi840.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi842.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi848.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi85.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi852.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi853.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi857.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi858.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi859.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi84.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi840.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi842.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi848.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi85.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi852.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi853.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi857.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi858.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi859.root $Step2Output 47" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi864.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi865.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi866.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi868.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi869.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi87.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi870.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi871.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi89.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi9.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi864.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi865.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi866.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi868.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi869.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi87.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi870.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi871.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi89.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi9.root $Step2Output 48" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

echo "Arguments = `pwd` /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi90.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi91.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi92.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi93.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi95.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi96.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi98.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/NoPU/Result_Lumi99.root /eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi90.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi91.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi92.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi93.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi95.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi96.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi98.root:/eos/user/c/chenyi/Share/17241_SmallSampleForMCTruthSeparate/PU/Result_Lumi99.root $Step2Output 49" >> $SubmissionFile
echo 'Output    = Log/Step2.out.$(Process)' >> $SubmissionFile
echo 'Error     = Log/Step2.err.$(Process)' >> $SubmissionFile
echo 'Log       = Log/Step2.log.$(Process)' >> $SubmissionFile
echo 'Queue' >> $SubmissionFile

condor_submit $SubmissionFile
