

default: RunAll

RunAll:
	# python3 RunOne.py --N -1 --ModelCov 1 --LikelihoodType 0 --CorrLength 0.1 --Tag _MVN_ModelCov_Corr
	# python3 RunOne.py --N -1 --ModelCov 1 --LikelihoodType 0 --CorrLength 0.0 --Tag _MVN_ModelCov_NoCorr
	# python3 RunOne.py --N -1 --ModelCov 0 --LikelihoodType 0 --CorrLength 0.1 --Tag _MVN_NoModelCov_Corr
	# python3 RunOne.py --N -1 --ModelCov 0 --LikelihoodType 0 --CorrLength 0.0 --Tag _MVN_NoModelCov_NoCorr
	# python3 RunOne.py --N -1 --ModelCov 0 --LikelihoodType 1 --CorrLength 0.0 --Tag _D2_NoModelCov_NoCorr
	# python3 RunOne.py --N -1 --ModelCov 0 --LikelihoodType 2 --CorrLength 0.0 --Tag _Chi2_NoModelCov_NoCorr
	# python3 RunOne.py --N -1 --ModelCov 0 --LikelihoodType 2 --CorrLength 0.0 --Tag _Chi2_NoModelCov_NoCorr_Nu1.5 --Nu 1.5
	python3 RunOne.py --N -1 --ModelCov 0 --LikelihoodType 2 --CorrLength 0.0 --Tag _Chi2_NoModelCov_NoCorr_Nu0.5 --Nu 0.5
	# python3 RunOne.py --N -1 --ModelCov 0 --LikelihoodType 2 --CorrLength 0.0 --Tag _Chi2_NoModelCov_NoCorr_Nu3.5 --Nu 3.5
	# python3 RunOne.py --N -1 --ModelCov 0 --LikelihoodType 2 --CorrLength 0.0 --Tag _Chi2_NoModelCov_NoCorr_Nu1.0 --Nu 1.0
