default: RunTest;

RunTest: TestCalculation.cpp
	g++ TestCalculation.cpp -o RunTest -I../../CommonCode/include ../../CommonCode/library/CalculateME_Part35.o ../../CommonCode/library/AngleConversion.o -I ~/FHeadHelperCode/RootMacros/ ~/FHeadHelperCode/RootMacros/Code/library/TauHelperFunctions3.o
