./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_0.root Result/AAData_0.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_1.root Result/AAData_1.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_10.root Result/AAData_2.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_11.root Result/AAData_3.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_12.root Result/AAData_4.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_13.root Result/AAData_5.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_14.root Result/AAData_6.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_15.root Result/AAData_7.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_16.root Result/AAData_8.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_17.root Result/AAData_9.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_18.root Result/AAData_10.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_19.root Result/AAData_11.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_2.root Result/AAData_12.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_20.root Result/AAData_13.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_21.root Result/AAData_14.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_22.root Result/AAData_15.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_23.root Result/AAData_16.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_24.root Result/AAData_17.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_25.root Result/AAData_18.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_26.root Result/AAData_19.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_27.root Result/AAData_20.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_28.root Result/AAData_21.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_29.root Result/AAData_22.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_3.root Result/AAData_23.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_30.root Result/AAData_24.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_31.root Result/AAData_25.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_32.root Result/AAData_26.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_33.root Result/AAData_27.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_34.root Result/AAData_28.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_35.root Result/AAData_29.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_36.root Result/AAData_30.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_37.root Result/AAData_31.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_38.root Result/AAData_32.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_4.root Result/AAData_33.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_5.root Result/AAData_34.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_6.root Result/AAData_35.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_7.root Result/AAData_36.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_8.root Result/AAData_37.root
./a.out /afs/cern.ch/user/c/chenyi/EOS/cms///store/group/cmst3/group/hintt/mverweij/CS/data/HIHardProbes/crab_HIHardProbes_v5/160313_203758/merge/HiForest_9.root Result/AAData_38.root
