DoStandardFit:
	jet_synchfit_x -inputDir Input/ -outputDir `pwd`/Output/ \
		-algo1 ak4pf -algo2 ak4pf \
		-highPU false -useNPU false -functionType standard -era TestEra

DoTestFit:
	jet_synchfit_x -inputDir Input/ -outputDir `pwd`/Output/ \
		-algo1 ak4pf -algo2 ak4pf \
		-highPU false -useNPU true -functionType standard -era TestEra


