GetConfiguration:
	cmsDriver.py step2 --mc --eventcontent AODSIM --datatier GEN-SIM-RECO --conditions auto:phase1_2018_realistic --step RAW2DIGI,L1Reco,RECO --nThreads 4 --geometry DB:Extended --era Run2_2018_pp_on_AA --no_exec
