#!/bin/sh

source ~/.bashrc

CurrentFolder=`pwd`

mkdir -p $CurrentFolder/BatchSubmit
mkdir -p $CurrentFolder/BatchResult

BinCount=80
BinMin=-0.9999
BinMax=0.9999

for i in `seq 1 $BinCount`
do
   WorkDir="/wntmp/yichen/Work/WorkArea_Fit_13162_${i}"
   FileName="$CurrentFolder/BatchSubmit/Submit_${i}.sh"

   # F2=`echo $BinMin $BinMax $BinCount $i | awk '{print $1 + ($2-$1)/($3-1)*($4-1)}' | awk '{if($1 < 0) {print $1} else {print -$1}}'`
   # F2=`echo $BinMin $BinMax $BinCount $i | awk '{print $1 + ($2-$1)/($3-1)*($4-1)}'`
   F2=`echo $BinMin $BinMax $BinCount $i | awk '{print $1 + ($2-$1)/($3-1)*($4-1)}'`
   F3=0
   AbsF2=`echo $F2 | awk '{if($1<0) {print -$1} else {print $1}}'`
   AbsF3=`echo $F3 | awk '{if($1<0) {print -$1} else {print $1}}'`
   F1=`echo $AbsF2 $AbsF3 | awk '{print 1-$1-$2}'`
   S2=`echo $F1 $F2 | awk '{print $2/$1}' | awk '{if($1 < 0) {print -$1} else {print $1}}'`
   S3=`echo $F1 $F3 | awk '{print $2/$1}' | awk '{if($1 < 0) {print -$1} else {print $1}}'`
   A2=`echo $F2 $S2 | awk '{if($1 > 0) {print sqrt($2)*(-3.276)} else {print -sqrt($2)*(-3.276)}}'`
   A3=`echo $F3 $S3 | awk '{if($1 > 0) {print sqrt($2)*(-5.042)} else {print -sqrt($2)*(-5.042)}}'`

   AL=0

   if [[ `echo "$F1 > 0" | bc` == "1" ]];
   then
      BatchPrefix > $FileName
      echo "" >> $FileName
      echo "echo \$HOSTNAME" >> $FileName
      echo "" >> $FileName
      echo "mkdir -p $WorkDir" >> $FileName
      echo "cd $WorkDir" >> $FileName
      echo "" >> $FileName
      echo "pwd" >> $FileName
      echo "" >> $FileName
      echo "cp -r $CurrentFolder/*cpp $WorkDir" >> $FileName
      echo "cp -r $CurrentFolder/*h $WorkDir" >> $FileName
      echo "cp -r $CurrentFolder/Trees $WorkDir" >> $FileName
      echo "cp -r $CurrentFolder/OldTrees $WorkDir" >> $FileName
      echo "cp -r $CurrentFolder/SyncTrees $WorkDir" >> $FileName
      echo "cp -r $CurrentFolder/ExoticToys $WorkDir" >> $FileName
      echo "" >> $FileName
      echo "rm $WorkDir/*.dh" >> $FileName
      echo "ln -s $CurrentFolder/../../BuildMap/13156_CollectNormalization/CombinedNormalization.dh $WorkDir/" >> $FileName
      echo "ln -s $CurrentFolder/../../BuildMap/13156_CollectNormalization/Normalization.dh $WorkDir/" >> $FileName
      echo "" >> $FileName
      echo "sh compile.sh" >> $FileName
      echo "" >> $FileName
      # echo "S7=Trees/SignalAll7TeV.root" >> $FileName
      # echo "B7=Trees/BackgroundAll7TeV.root" >> $FileName
      # echo "Z7=OldTrees/HZZEventFitFormat_MC_ZJets_8TeV.root" >> $FileName
      # echo "G7=OldTrees/HZZEventFitFormat_ggZZAll.root" >> $FileName
      # echo "S8=Trees/SignalAll8TeV.root" >> $FileName
      # echo "B8=Trees/BackgroundAll8TeV.root" >> $FileName
      # echo "Z8=OldTrees/HZZEventFitFormat_MC_ZJets_8TeV.root" >> $FileName
      # echo "G8=OldTrees/HZZEventFitFormat_ggZZAll.root" >> $FileName
      # echo "S7=SyncTrees/SyncToys_7TeV_SMSignal.root" >> $FileName
      echo "B7=SyncTrees/SyncToys_7TeV_Bkg.root" >> $FileName
      echo "Z7=SyncTrees/SyncToys_7TeV_Bkg.root" >> $FileName
      echo "G7=SyncTrees/SyncToys_7TeV_Bkg.root" >> $FileName
      # echo "S8=SyncTrees/SyncToys_8TeV_SMSignal.root" >> $FileName
      echo "B8=SyncTrees/SyncToys_8TeV_Bkg.root" >> $FileName
      echo "Z8=SyncTrees/SyncToys_8TeV_Bkg.root" >> $FileName
      echo "G8=SyncTrees/SyncToys_8TeV_Bkg.root" >> $FileName
      echo "S7=ExoticToys/SyncToys_7TeV_All_Mixed_fa2.root" >> $FileName
      echo "S8=ExoticToys/SyncToys_8TeV_All_Mixed_fa2.root" >> $FileName
      echo "" >> $FileName
      echo "time ./PerformFitsMixedZX \$S7 \$B7 \$Z7 \$G7 \$S8 \$B8 \$Z8 \$G8 $A2 $A3 0 0 0 0 $AL -1" >> $FileName
      echo "mv OutputFile.root $CurrentFolder/BatchResult/FA3Result_${i}.root" >> $FileName
      echo "" >> $FileName
      # echo "time ./PerformFits Trees/SyncToys_7TeV_ExoticSignal.root Trees/SyncToys_7TeV_Bkg.root Trees/SyncToys_7TeV_Bkg.root Trees/SyncToys_7TeV_Bkg.root \\" >> $FileName
      # echo "   Trees/SyncToys_8TeV_ExoticSignal.root Trees/SyncToys_8TeV_Bkg.root Trees/SyncToys_8TeV_Bkg.root Trees/SyncToys_8TeV_Bkg.root \\" >> $FileName
      # echo "   $A2 $A3 0 0 0 0 0 -1" >> $FileName
      # echo "mv OutputFile.root $CurrentFolder/BatchResult/ExoticLikelihoodFile_$i.root" >> $FileName
      echo "" >> $FileName
      echo "rm -r $WorkDir/*" >> $FileName
   fi
done



