export LD_LIBRARY_PATH=/Users/yichen/Programs/root/build/lib:/Users/yichen/FHeadHelperCode/RootMacros

TestRun: Execute
	./Execute


Execute: DrawEnvelope.cpp
	CompileRootMacro DrawEnvelope.cpp Execute
